FROM ubuntu:16.04


# Installing Packages
RUN apt-get update && \
    apt-get install -y telnet && \
    apt-get install -y curl && \
    apt-get install -y ffmpeg && \
    rm -rf /var/lib/apt/lists/* 

